title: "RobDWaller Blog and Profile Website: A Developer and Head of Tech"
page_title: "RobDWaller A Developer"
description: "I am a PHP and JavaScript Developer and Head of Tech at a communications agency in London. I also built Twitter's largest anti-bot app."
url: http://robdwaller.github.io
twitter: "@robdwaller"
