title: "RobDWaller Blog and Profile Website: A Developer and Head of Tech"
page_title: "RobDWaller A Developer"
description: "I am a software developer and manager with nearly a decade and a half of experience. I also built Twitter's largest anti-bot app."
url: http://robdwaller.github.io
twitter: "@robdwaller"

collections:
    talks:
        output: true
        permalink: /:collection/:name
