title: "Rob Waller Blog and Profile Website: A Developer, Manager and Architect"
page_title: "RobDWaller A Developer"
description: "I am a developer with a passion for testing. I've been coding for 15 years, I've run my own business and been a Head of Technology."
url: http://robdwaller.github.io
twitter: "@robdwaller"

collections:
    talks:
        output: true
        permalink: /:collection/:name
