title: "RobDWaller Blog and Profile Website: Developer and Head of Tech"
description: "I am a PHP and JavaScript Developer and Head of Tech at a communications agency in London."
url: http://robdwaller.github.io
twitter: "@robdwaller"
