title: "Rob Waller Blog and Profile Website: Director, Architect and Software Developer"
page_title: "RobDWaller A Director of Software Engineering"
description: "Director, Product Engineering at TELUS Health. Coding for 15+ years, a TDD advocate, PHP fan, with a History Degree."
url: http://robdwaller.github.io
twitter: "@robdwaller"

collections:
    talks:
        output: true
        permalink: /:collection/:name
