title: "Rob Waller Blog and Profile Website: A Developer, Manager and Architect"
page_title: "RobDWaller A Developer"
description: "Head of Backend Development for the LifeWorks App. Coding for 15+ years, a TDD advocate, PHP fan, with an interest in Complexity Theory."
url: http://robdwaller.github.io
twitter: "@robdwaller"

collections:
    talks:
        output: true
        permalink: /:collection/:name
